name: Rust

on:
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

#env:
#  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    #- name: Install NEAR CLI
    #  run: npm install -g near-cli
    
    #- name: Add wasm target to your toolchain
    #  run: rustup target add wasm32-unknown-unknown
    
    #- name: Build
    #  run: cargo build --target wasm32-unknown-unknown --release
      
    - name: Set Keys
      run: sh ./script.sh
          
    - name: Check Keys
      run: |
        cd ~/.near-credentials
        ls -a
        cat fundingaccount05.testnet.json
      
    #- name: Deploy
    #  run: |
    #   near deploy --wasmFile ./target/wasm32-unknown-unknown/release/rust_ci_example.wasm --accountId fundingaccount05.testnet
       
    
    #- name: Run tests
    #  run: cargo test --verbose
