name: Rust

on:
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

#env:
#  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Install NEAR CLI
      run: npm install -g near-cli
    
    - name: Add wasm target to your toolchain
      run: rustup target add wasm32-unknown-unknown
    
    - name: Build
      run: cargo build --target wasm32-unknown-unknown --release
      
    - name: Deploy
      run: | 
       export WASM_PATH="$(find ./target/wasm32-unknown-unknown/release/ -maxdepth 1 -name "*.wasm")" \
       near dev-deploy $WASM_PATH
    
    #- name: Run tests
    #  run: cargo test --verbose
