name: Rust

on:
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

#env:
#  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Install NEAR CLI
      run: npm install -g near-cli
    
    - name: Add wasm target to your toolchain
      run: rustup target add wasm32-unknown-unknown
    
    - name: Build
      run: cargo build --target wasm32-unknown-unknown --release
      
    - name: Set Keys
      run: sh ./script.sh
          
    - name: Check Keys
      run: |
        cd ~/.near-credentials/testnet
        ls -a
        cat subaccount04.testaccount14.testnet.json
        
    - uses: dawidd6/action-download-artifact@v2.17.0   # make it dont stop if fail
      with:
        github_token: ${{secrets.TOKEN}}
        workflow: build.yml
        name: subaccount-keys
        path: ~/.near-credentials/testnet/x4.subaccount04.testaccount14.testnet.json
        workflow_conclusion: failed
        
    - name: Delete/Create subaccounts
      if: always()
      run: sh ./check.sh
      
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: subaccount-keys
        path: ~/.near-credentials/testnet/x4.subaccount04.testaccount14.testnet.json
      
    - name: Deploy
      if: always()
      run: |
       near deploy --wasmFile ./target/wasm32-unknown-unknown/release/rust_ci_example.wasm --accountId x4.subaccount04.testaccount14.testnet
       
    
    #- name: Run tests
    #  run: cargo test --verbose
