name: Rust Near 

on:
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  
env:
  CONTRACT_ACCOUNT_ID: x21.subaccount04.testaccount14.testnet

jobs:
  build: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Install NEAR CLI
      run: npm install -g near-cli
    
    - name: Add wasm target to your toolchain
      run: rustup target add wasm32-unknown-unknown
    
    - name: Build
      run: cargo build --target wasm32-unknown-unknown --release
      
    - name: Set Keys
      run: sh ./script.sh
          
    - name: Check Keys
      run: |
        cd ~/.near-credentials/testnet
        ls -a
        cat subaccount04.testaccount14.testnet.json
    
    - name: Download artifact credentials
      uses: dawidd6/action-download-artifact@v2
      continue-on-error: True
      with:
          workflow: build.yml
          branch: master
          name: credentials
          path: ../../../.near-credentials/testnet/
    
    - name: Check artifact
      run: |
        cd
        ls -a
        find -iname $CONTRACT_ACCOUNT_ID.json
        
    - name: Delete subaccount
      continue-on-error: True
    #  if: steps.cache.outputs.cache-hit == 'true'
      run: near delete $CONTRACT_ACCOUNT_ID subaccount04.testaccount14.testnet
      
    - name: Create or recreate subaccount
      run: |
       near create-account $CONTRACT_ACCOUNT_ID --masterAccount subaccount04.testaccount14.testnet
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: credentials
        path: ~/.near-credentials/testnet/$CONTRACT_ACCOUNT_ID.json
    
    - name: Deploy
      run: |
       near deploy --wasmFile ./target/wasm32-unknown-unknown/release/rust_ci_example.wasm --accountId $CONTRACT_ACCOUNT_ID
       
    
    #- name: Run tests
    #  run: cargo test --verbose
