name: Rust

on:
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

#env:
#  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    #- name: Install NEAR CLI
    #  run: npm install -g near-cli
    
    #- name: Add wasm target to your toolchain
    #  run: rustup target add wasm32-unknown-unknown
    
    #- name: Build
    #  run: cargo build --target wasm32-unknown-unknown --release
      
    - name: Set Keys
      run: |
        echo "donde inicio"
        pwd
        echo "creo la carpeta de credenciales"
        mkdir ~/.near-credentials
        echo "me muevo a la carpeta de credenciales"
        cd ~/.near-credentials
        echo "donde estoy ahora? debería estar en la carpeta de credenciales"
        pwd
        echo "qué hay dentro de la carpeta de credenciales"
        ls -a
        touch fundingaccount05.testnet.json
        echo "sigo en la misma carpeta?"
        pwd
        echo "qué hay ahora dentro?"
        ls -a
        echo "trato de llenar el archivo de keys"
    
        uses: DamianReeves/write-file-action
        with:
          path: ${{env.home}}//runner/.near-credentials/fundingaccount05.testnet.json
          contents: |
            echo "{account_id:fundingaccount05.testnet,public_key:ed25519:Fthv63N3mgjbQZLBfzyRQkgghUWhxnMu7dkyy3KFxijs,private_key:ed25519:1VMwoTWDngRQX992gyFd53ZAALBV4dtmvoiuapmceAYLAFvty63JGrcwEeLshqNgM3cVaXugoQJcfVzHhVvmPgM}%"
          write-mode: append
          
    - name: Check Keys
      run: |
        cat ${{env.home}}//runner/.near-credentials/fundingaccount05.testnet.json
      
    #- name: Deploy
    #  run: |
    #   near deploy --wasmFile ./target/wasm32-unknown-unknown/release/rust_ci_example.wasm --accountId fundingaccount05.testnet
       
    
    #- name: Run tests
    #  run: cargo test --verbose
