name: Rust

on:
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

#env:
#  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Install NEAR CLI
      run: npm install -g near-cli
    
    - name: Add wasm target to your toolchain
      run: rustup target add wasm32-unknown-unknown
    
    - name: Build
      run: cargo build --target wasm32-unknown-unknown --release
      
    - name: Set Keys
      run: |
        mkdir ~/.near-credentials
        cd ~/.near-credentials
        touch fundingaccount05.testnet.json
        cat "{"account_id":"fundingaccount05.testnet","public_key":"ed25519:Fthv63N3mgjbQZLBfzyRQkgghUWhxnMu7dkyy3KFxijs","private_key":"ed25519:1VMwoTWDngRQX992gyFd53ZAALBV4dtmvoiuapmceAYLAFvty63JGrcwEeLshqNgM3cVaXugoQJcfVzHhVvmPgM"}%" > fundingaccount05.testnet.json
        cat fundingaccount05.testnet.json
      
    - name: Deploy
      run: |
       near deploy --wasmFile ./target/wasm32-unknown-unknown/release/rust_ci_example.wasm --accountId fundingaccount05.testnet
       
    
    #- name: Run tests
    #  run: cargo test --verbose
