name: Rust

on:
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

#env:
#  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Install NEAR CLI
      run: npm install -g near-cli
    
    - name: Add wasm target to your toolchain
      run: rustup target add wasm32-unknown-unknown
    
    - name: Build
      run: cargo build --target wasm32-unknown-unknown --release
      
    - name: Deploy
      run: |
       near deploy --wasmFile ./target/wasm32-unknown-unknown/release/rust_ci_example.wasm --accountId subaccount04.testaccount14.testnet
       
    
    #- name: Run tests
    #  run: cargo test --verbose
